
export const drawerWidth = 240;

export const borderStyle = {
    top: { style: "thin" },
    bottom: { style: "thin" },
    left: { style: "thin" },
    right: { style: "thin" }
};

export const alignmentStyle = {
    horizontal: "center"
};

export const exportCommonStyle = {
    font: { color: {rgb: "ffffff"} },
    fill: { patternType: "solid", fgColor: {rgb: "3461eb"} },
    border: borderStyle,
    alignment: alignmentStyle
}

export const formTypes = {

    newVehicle: 'NEW_VEHICLE',
    newUser: 'NEW_USER',
    newPenalty: 'NEW_PENALTY',
    newPrint: 'NEW_PRINT',
    login: 'LOGIN',
    signUp: 'SIGN_UP',
    forgotPassword: 'FORGOT_PASSWORD',
    newPassword: 'NEW_PASSWORD',
    newAutoGeneratedForm: 'NEW_AUTO_GENERATED_FORM',
    autoGenerateForm: 'AUTO_GENERATE_FORM',
}

export const pageType = {
    vehicle: {
        type: 'VEHICLE',
        sortByOptions: [
            "Plate Number",
            "creation date"
        ],
    },
    penalty: {
        type: 'PENALTY',
        sortByOptions: [
            "Plate Number", "receipt no", "owner name", "penalty date"
        ],
    },
    users: {
        type: 'USERS',
        sortByOptions: [
            "Name",
            "creation date"
        ],
    },
}


export const excelFileType = {
    //attached to excel to identify page type. for menu data, the added menu will be used as file type
    vehicle: "VEHICLE",
    penalty: "PENALTY",
}

export const paymentStatus = ['ÖDENDİ', "BEKLEMEDE"]

export const accessSecurity = [
    'GENEL SEKRETER YARDIMCILIĞI (1)',
    'GENEL SEKRETER YARDIMCILIĞI (2)',
    'GENEL SEKRETER YARDIMCILIĞI (3)',
    'GENEL SEKRETER YARDIMCILIĞI (4)',
    'GENEL SEKRETER YARDIMCILIĞI (5)',
    'GENEL SEKRETER YARDIMCILIĞI (6)',
    'GENEL SEKRETER YARDIMCILIĞI (7)',
    'BAŞKANLIK'
]

export const departments = [
    'ZABITA DAİRESİ BAŞKANLIĞI',
    'ULAŞIM DAİRESİ BAŞKANLIĞI',
    'DESTEK HİZMETLERİ DAİRESİ BAŞKANLIĞI',
    'SAĞLIK DAİRESİ BAŞKANLIĞI',
    'ÇEVRE KORUMA VE KONTROL DAİRESİ BAŞKANLIĞI',
    'MEZARLIKLAR DAİRESİ BAŞKANLIĞI',
    'SOSYAL HİZMETLER DAİRESİ BAŞKANLIĞI',
    'PARK BAHÇE VE YEŞİL ALANLAR DAİRESİ BAŞKANLIĞI',
    'İNSAN KAYNAKLARI VE EĞİTİM DAİRESİ BAŞKANLIĞI',
    'YOL BAKIM VE ALTYAPI KOORDİNASYON DAİRESİ BAŞKANLIĞI',
    'YAZI İŞLERİ VE KARARLAR DAİRESİ BAŞKANLIĞI',
    'TEFTİŞ KURUL BAŞKANLIĞI',
    'TARIMSAL HİZMETLER DAİRESİ BAŞKANLIĞI',
    'İTFAİYE DAİRESİ BAŞKANLIĞI',
    'İMAR VE ŞEHİRCİLİK DAİRESİ BAŞKANLIĞI',
    'BASIN YAYIN VE HALKLA İLİŞKİLER DAİRESİ BAŞKANLIĞI',
    'KURUMSAL GELİŞİM VE YÖNETİM SİSTEMLERİ DAİRESİ BAŞKANLIĞI',
    'KÜLTÜR DAİRESİ BAŞKANLIĞI',
    'SATINALMA DAİRESİ BAŞKANLIĞI'
]

export const units = [
    'ANADOLU YAKASI ZABITA ŞUBE MÜDÜRLÜĞÜ',
    'AVRUPA YAKASI ZABITA ŞUBE MÜDÜRLÜĞÜ',
    'DESTEK HİZMETLERİ ŞUBE MÜDÜRLÜĞÜ',
    'SAĞLIK VE HIFZISSIHA ŞUBE MÜDÜRLÜĞÜ',
    'ÖZEL KALEM MÜDÜRLÜĞÜ',
    'KADIN VE AİLE HİZMETLERİ ŞUBE MÜDÜRLÜĞÜ',
    'HALKLA İLİŞKİLER ŞUBE MÜDÜRLÜĞÜ',
    'ANADOLU YAKASI PARK VE BAHÇELER ŞUBE MÜDÜRLÜĞÜ',
    'AVRUPA YAKASI PARK VE BAHÇELER ŞUBE MÜDÜRLÜĞÜ',
    'ACİL YARDIM VE CANKURTARMA ŞUBE MÜDÜRLÜĞÜ',
    'MAKİNE İKMAL ŞUBE MÜDÜRLÜĞÜ',
    'VETERİNER HİZMETLERİ ŞUBE MÜDÜRLÜĞÜ',
    'SOSYAL HİZMETLER ŞUBE MÜDÜRLÜĞÜ',
    'MEZARLIKLAR DESTEK HİZMETLERİ ŞUBE MÜDÜRLÜĞÜ',
    'TESİSLER BAKIM VE ONARIM ŞUBE MÜDÜRLÜĞÜ',
    'GÜVENLİK ŞUBE MÜDÜRLÜĞÜ',
    'SATINALMA ŞUBE MÜDÜRLÜĞÜ',
    'ENERJİ YÖNETİMİ VE AYDINLATMA ŞUBE MÜDÜRLÜĞÜ',
    'MAKİNE İKMAL ŞUBE MÜDÜRLÜĞÜ',
    'İŞLETMELER ŞUBE MÜDÜRLÜĞÜ',
    'LOJİSTİK YÖNETİMİ VE TERMİNALLER ŞUBE MÜDÜRLÜĞÜ',
    'EĞİTİM ŞUBE MÜDÜRLÜĞÜ',
    'İNSAN KAYNAKLARI ŞUBE MÜDÜRLÜĞÜ',
    'İSTANBUL DARÜLACEZE ŞUBE MÜDÜRLÜĞÜ',
    'HUKUK MÜŞAVİRLİĞİ',
    'ENGELLİLER ŞUBE MÜDÜRLÜĞÜ',
    'YEŞİL ALAN VE TESİSLER YAPIM ŞUBE MÜDÜRLÜĞÜ',
    'AVRUPA YAKASI İTFAİYE ŞUBE MÜDÜRLÜĞÜ',
    'ANADOLU YAKASI İTFAİYE ŞUBE MÜDÜRLÜĞÜ',
    'ÇEVRE KORUMA ŞUBE MÜDÜRLÜĞÜ',
    'İHALE İŞLERİ ŞUBE MÜDÜRLÜĞÜ',
    'RUHSAT VE DENETİM ŞUBE MÜDÜRLÜĞÜ',
    'HAL ŞUBE MÜDÜRLÜĞÜ',
    'BOĞAZİÇİ İMAR ŞUBE MÜDÜRLÜĞÜ',
    'TARIM VE SU ÜRÜNLERİ ŞUBE MÜDÜRLÜĞÜ',
    'ŞEHİT YAKINLARI VE GAZİLERLE İLİŞKİLER ŞUBE MÜDÜRLÜĞÜ',
    'ULAŞIM KOORDİNASYON ŞUBE MÜDÜRLÜĞÜ',
    'İŞ SAĞLIĞI VE GÜVENLİĞİ ŞUBE MÜDÜRLÜĞÜ',
    'HAL ŞUBE MÜDÜRLÜĞÜ',
    'ŞEHİR TİYATROLARI ŞUBE MÜDÜRLÜĞÜ',
    'GELİRLER ŞUBE MÜDÜRLÜĞÜ',
    'GİDERLER ŞUBE MÜDÜRLÜĞÜ',
    'HALKLA İLİŞKİLER ŞUBE MÜDÜRLÜĞÜ',
    'TRAFİK ŞUBE MÜDÜRLÜĞÜ',
    'AB İLİŞKİLERİ ŞUBE MÜDÜRLÜĞÜ',
    'ULAŞIM PLANLAMA ŞUBE MÜDÜRLÜĞÜ',
    'FİNANSMAN ŞUBE MÜDÜRLÜĞÜ',
    'MUHTARLIKLAR ŞUBE MÜDÜRLÜĞÜ',
    'BASIN YAYIN ŞUBE MÜDÜRLÜĞÜ',
    'STRATEJİ GELİŞTİRME ŞUBE MÜDÜRLÜĞÜ',
    'KÜLTÜR VARLIKLARI PROJELER ŞUBE MÜDÜRLÜĞÜ',
    'KADIN VE AİLE HİZMETLERİ ŞUBE MÜDÜRLÜĞÜ',
    'ARŞİV ŞUBE MÜDÜRLÜĞÜ',
    'KENTSEL EKOLOJİK SİSTEMLER ŞUBE MÜDÜRLÜĞÜ',
    'ANADOLU YAKASI RAYLI SİSTEMLER ŞUBE MÜDÜRLÜĞÜ',
    'AVRUPA YAKASI RAYLI SİSTEMLER ŞUBE MÜDÜRLÜĞÜ',
    'HAYAT BOYU ÖĞRENME ŞUBE MÜDÜRLÜĞÜ',
    'TOPLU ULAŞIM HİZMETLERİ ŞUBE MÜDÜRLÜĞÜ',
    'BİRİM FİYAT VE STANDARTLAR ŞUBE MÜDÜRLÜĞÜ',
    'KESİN HESAP ŞUBE MÜDÜRLÜĞÜ',
    'ENCÜMEN ŞUBE MÜDÜRLÜĞÜ',
    'YAPI İŞLERİ ŞUBE MÜDÜRLÜĞÜ',
    'ALTYAPI KOORDİNASYON ŞUBE MÜDÜRLÜĞÜ',
    'ORKESTRALAR ŞUBE MÜDÜRLÜĞÜ',
    'DENİZ HİZMETLERİ ŞUBE MÜDÜRLÜĞÜ',
    'KÜTÜPHANE VE MÜZELER ŞUBE MÜDÜRLÜĞÜ',
    'KORUMA UYGULMA VE DENETİM ŞUBE MÜDÜRLÜĞÜ',
    'PLANLAMA ŞUBE MÜDÜRLÜĞÜ',
    'İSTANBUL ŞEHİRCİLİK ATÖLYESİ ŞUBE MÜDÜRLÜĞÜ',
    'LEVAZIM VE AYNİYAT ŞUBE MÜDÜRLÜĞÜ',
    'YAZI İŞLERİ ŞUBE MÜDÜRLÜĞÜ',
    'MECLİS ŞUBE MÜDÜRLÜĞÜ',
    'SATINALMA ŞUBE MÜDÜRLÜĞÜ',
    'İŞ SAĞLIĞI VE GÜVENLİĞİ ŞUBE MÜDÜRLÜĞÜ',
    'KAMULAŞTIRMA ŞUBE MÜDÜRLÜĞÜ',
    'EMLAK ŞUBE MÜDÜRLÜĞÜ',
    'GENÇLİK SPOR ŞUBE MÜDÜRLÜĞÜ'
]

export const cancelationStatus = ["İPTAL EDİLDİ", "BEKLEMEDE"]

export const signUpTextfields  = [
    {
        placeholder: "Isim",
        name: "name",
        type: "text"

    },
    {
        placeholder: "Soyisim",
        name: "surname",
        type: "text"

    },
    {
        placeholder: "E-post",
        name: "email",
        type: "email"

    },
    {
        placeholder: "Parola",
        name: "password",
        type: "password"

    },
]


export const vehicleTextFields = [
    {
        placeholder: "Plaka No",
        name: "plate_number"

    },
    {
        placeholder: "Araç Grubu",
        name: "vehicle_group"

    },
    {
        placeholder: "Marka-Model",
        name: "brand_model"

    },
    {
        placeholder: "Şase No",
        name: "chassis_number"
    },
    {
        placeholder: "Motor No",
        name: "motor_number"
    },
    {
        placeholder: "Model Yılı",
        name: "model_year"
    },
    {
        placeholder: "Renk",
        name: "color"
    },
    {
        placeholder: "Dosya No",
        name: "file_number"
    },
    {
        placeholder: "Künye",
        name: "tag"
    },
    {
        placeholder: "Demirbaş No",
        name: "asset_number"
    },
    {

        placeholder: "CEZA TARİHİ",
        name: "delivery_date"
    }
]

export const vehicleSelectFields = [

    {
        name: "unit_garage_status",
        label: "Birim",
        menuItem: [

            {
                value: "İstaç A.Ş"
            },
            {
                value: "İgdaş A.Ş"
            },
            {
                value: "Avrupa yakası Zabıta",
            },
            {
                value: "Avrupa yakası Mezarlıklar",
            },
            {
                value: "Makine ikmal",
            },
            {
                value: "Destek Hizmetleri",
            },
            {
                value: "İsbak A.Ş",
            },
            {
                value: "Anadolu yakası Zabıta",
            },
            {
                value: "Anadolu yakası Mezarlıklar",
            },
            {
                value: "Ağaç A.Ş",
            },
            {
                value: "İsfalt A.Ş",
            },

        ]
    },
    {
        name: "vehicle_status",
        label: "araç durum",
        menuItem: [
            {
                value: 'Serviste',
            },
            {
                value : 'zimmetli',
            },
            {
                value : 'bakimda',
            },
            {
                value : 'zimmetli degil',
            }
        ]
    },
    {
        name: "vehicle_type",
        label: "araç tipi",
        menuItem: [

            {
                value: "kiralik"
            },
            {
                value: "Ö.MAKBUZ"
            },
            {
                value: "ihale yolu"
            },
            {
                value: "Protokol"
            },
            {
                value: "yedek"
            },
        ]
    },

]


export const penaltyTextFields = [

    {
        placeholder: "PLAKA NO",
        name: "plate_number",
        type: "text"

    },
    {
        placeholder: "MAKBUZ",
        name: "receipt_number",
        type: "text"

    },
    {
        placeholder: "CEZA TARİHİ",
        name: "penalty_date",
        type: "text"

    },
    {
        placeholder: "TEBLİĞ TARİHİ ",
        name: "notification_date",
        type: "text"

    },
    {
        placeholder: "CEZA TUTAR",
        name: "penalty",
        type: "text"

    },
    {
        placeholder: "PESİN TUTAR ",
        name: "payment_amount",
        type: "text"

    },
    {
        placeholder: "CEZA MADDESİ ",
        name: "penalty_article",
        type: "text"

    },
    {
        placeholder: "CEZA SAATİ ",
        name: "penalty_hour",
        type: "text"

    },
    {
        placeholder: "GENEL SEKRETER YARDIMCILIĞI",
        name: "boss",
        type: "text"

    },

    {
        placeholder: "DAİRE BAŞKANLIKLARI",
        name: "department",
        type: "text"

    },
    {
        placeholder: "MÜDÜRLÜK ",
        name: "unit",
        type: "text"

    },
    {
        placeholder: "ALTBIRIM ",
        name: "sub_depart",
        type: "text"

    },
    {
        placeholder: "İSİM-SOYİSİM ",
        name: "name",
        type: "text"

    },
    {
        placeholder: "ÖDEME YAPAN",
        name: "paying",
        type: "text"

    },
    {
        placeholder: "ÖDEME TARİHİ",
        name: "payment_date",
        type: "text"

    },
    {
        placeholder: "KARAR TARİHİ",
        name: "decision_date",
        type: "text"

    },
    {
        placeholder: "FİRMA",
        name: "company",
        type: "text"

    },
    {
        placeholder: "TALEP NO",
        name: "request_no",
        type: "text"

    },
    {
        placeholder: "BİRİM NO",
        name: "unit_no",
        type: "text"

    },
    {
        placeholder: "İBB NO",
        name: "imm_no",
        type: "text"

    },
    {
        placeholder: "BİRİME GELİŞ TARİHİ",
        name: "arrival_date",
        type: "text"

    },
    {
        placeholder: "İBB KAYIT TARİHİ ",
        name: "registration_date",
        type: "text"

    },
    {
        placeholder: "NOT ",
        name: "note",
        type: "text"

    },
]

export const penaltyTextFields1 = [

    {
        placeholder: "PLAKA NO",
        name: "plate_number",
        type: "text"

    },

    {
        placeholder: "GENEL SEKRETER YARDIMCILIĞI",
        name: "boss",
        type: "text"

    },

    {
        placeholder: "DAİRE BAŞKANLIKLARI",
        name: "department",
        type: "text"

    },

    {
        placeholder: "Altbirim ",
        name: "sub_depart",
        type: "text"

    },

    {
        placeholder: "MAKBUZ",
        name: "receipt_number",
        type: "text"

    },
    {
        placeholder: "CEZA TARİHİ",
        name: "penalty_date",
        type: "text"

    },
    {
        placeholder: "CEZA SAATİ ",
        name: "penalty_hour",
        type: "text"

    },
    {
        placeholder: "TEBLİĞ TARİHİ ",
        name: "notification_date",
        type: "text"

    },
    {
        placeholder: "CEZA TUTAR",
        name: "penalty",
        type: "text"

    },
    {
        placeholder: "PESİN TUTAR ",
        name: "payment_amount",
        type: "text"

    },
    // {
    //     placeholder: "CEZA MADDESİ ",
    //     name: "penalty_article",
    //     type: "text"

    // // },
    // {
    //     placeholder: "Müdürlük ",
    //     name: "unit",
    //     type: "text"

    // },
    // {
    //     placeholder: "İSİM-SOYİSİM ",
    //     name: "name",
    //     type: "text"

    // },
    // {
    //     placeholder: "İBB KAYIT TARİHİ ",
    //     name: "registration_date",
    //     type: "text"

    // },
    // {
    //     placeholder: "BİRİME GELİŞ TARİHİ",
    //     name: "arrival_date",
    //     type: "text"

    // },
    // {
    //     placeholder: "İBB NO",
    //     name: "imm_no",
    //     type: "text"

    // },
    // {
    //     placeholder: "TALEP NO",
    //     name: "request_no",
    //     type: "text"

    // },
    // {
    //     placeholder: "BİRİM NO",
    //     name: "unit_no",
    //     type: "text"

    // },
    // {
    //     placeholder: "FİRMA",
    //     name: "company",
    //     type: "text"

    // },
    // {
    //     placeholder: "KARAR TARİHİ",
    //     name: "decision_date",
    //     type: "text"

    // },
    // {
    //     placeholder: "ÖDEME TARİHİ",
    //     name: "payment_date",
    //     type: "text"

    // },
    // {
    //     placeholder: "ÖDEME YAPAN",
    //     name: "paying",
    //     type: "text"

    // },
    // {
    //     placeholder: "NOT ",
    //     name: "note",
    //     type: "text"

    // },
]

export const penaltyTextFields2 = [

    // {
    //     placeholder: "PLAKA NO",
    //     name: "plate_number",
    //     type: "text"

    // },

    // {
    //     placeholder: "GENEL SEKRETER YARDIMCILIĞI",
    //     name: "boss",
    //     type: "text"

    // },

    // {
    //     placeholder: "DAİRE BAŞKANLIKLARI",
    //     name: "department",
    //     type: "text"

    // },

    // {
    //     placeholder: "Altbirim ",
    //     name: "sub_depart",
    //     type: "text"

    // },

    // {
    //     placeholder: "MAKBUZ",
    //     name: "receipt_number",
    //     type: "text"

    // },
    // {
    //     placeholder: "CEZA TARİHİ",
    //     name: "penalty_date",
    //     type: "text"

    // },
    // {
    //     placeholder: "CEZA SAATİ ",
    //     name: "penalty_hour",
    //     type: "text"

    // },
    // {
    //     placeholder: "TEBLİĞ TARİHİ ",
    //     name: "notification_date",
    //     type: "text"

    // },
    // {
    //     placeholder: "CEZA TUTAR",
    //     name: "penalty",
    //     type: "text"

    // },

    // {
    //     placeholder: "PESİN TUTAR ",
    //     name: "payment_amount",
    //     type: "text"

    // },
    // {
    //     placeholder: "CEZA MADDESİ ",
    //     name: "penalty_article",
    //     type: "text"

    // },
    {
        placeholder: "Müdürlük ",
        name: "unit",
        type: "text"

    },
    {
        placeholder: "İSİM-SOYİSİM ",
        name: "name",
        type: "text"

    },
    {
        placeholder: "İBB KAYIT TARİHİ ",
        name: "registration_date",
        type: "text"

    },
    {
        placeholder: "BİRİME GELİŞ TARİHİ",
        name: "arrival_date",
        type: "text"

    },
    {
        placeholder: "İBB NO",
        name: "imm_no",
        type: "text"

    },
    {
        placeholder: "TALEP NO",
        name: "request_no",
        type: "text"

    },
    {
        placeholder: "BİRİM NO",
        name: "unit_no",
        type: "text"

    },
    {
        placeholder: "FİRMA",
        name: "company",
        type: "text"

    },
    {
        placeholder: "KARAR TARİHİ",
        name: "decision_date",
        type: "text"

    },
    {
        placeholder: "ÖDEME TARİHİ",
        name: "payment_date",
        type: "text"

    },
    {
        placeholder: "ÖDEME YAPAN",
        name: "paying",
        type: "text"

    },
    {
        placeholder: "NOT ",
        name: "note",
        type: "text"

    },
]


export const otherFields = [
    {
        name: 'delivery_date',
        placeholder: 'teslim tarihi'
    },
    {
        name: 'updated_at',
        placeholder: 'güncellendi'
    },
    {
        name: 'created_at',
        placeholder: 'oluşturulma tarihi'
    },
    {
        name: 'notification_date',
        placeholder: 'TEBLİG TARİHİ'
    },
    {
        name: 'status',
        placeholder: 'ÖDEME DURUMU'
    },
    {
        name: 'payment_date',
        placeholder: 'ÖDEME TARİHİ'
    },
    {
        name: 'penalty_date',
        placeholder: 'CEZA TARİHİ'
    },
    {
        name: 'penalty_hour',
        placeholder: 'CEZA-SAAT'
    },
    {
        name: 'role',
        placeholder: 'rol'
    },
    {
        name: "vehicle_type",
        placeholder: "Araç Tipi",
    },
    {

        name: "unit_garage_status",
        placeholder: "Birim",
    },
    {

        name: "vehicle_status",
        placeholder: "araç durum",
    },
    {

        name: "equipment",
        placeholder: "araç ekipmanları",
    },
    {

        name: "cancelation_status",
        placeholder: "İptal durum",
    },
    {
        name:'image_url',
        placeholder: 'resim'
    }

]

export const __Dates = [
    {

        name: "Monday",
        placeholder: "Pazartesi",
    },
    {

        name: "Tuesday",
        placeholder: "Salı",
    },
    {

        name: "Wednesday",
        placeholder: "Çarşamba",
    },
    {

        name: "Thursday",
        placeholder: "Perşembe",
    },
    {

        name: "Friday",
        placeholder: "Cuma",
    },
    {

        name: "Saturday",
        placeholder: "Cumartesi",
    },
    {

        name: "Sunday",
        placeholder: "Pazar",
    },
]


export const printData = [

    {
        name: "PLAKA",
        placeholder: "PLAKA",
        type: "text",

    },
    {
        name: "MAKBUZ NO",
        placeholder: "MAKBUZ NO",
        type: "text",

    },
    {
        name: "TEBLİĞ TARİHİ",
        placeholder: "TEBLİĞ TARİHİ",
        type: "text",

    },
    {
        name: "CEZA TARİHİ",
        placeholder: "CEZA TARİHİ",
        type: "text",

    },
    {
        name: "CEZA SAATİ",
        placeholder: "CEZA SAATİ",
        type: "text",

    },
    {
        name: "CEZA MADDESİ",
        placeholder: "CEZA MADDESİ",
        type: "text",

    },
    {
        name: "CEZA TUTARI",
        placeholder: "CEZA TUTARI",
        type: "text",

    },
    {
        name: "PEŞİN TUTAR",
        placeholder: "PEŞİN TUTAR",
        type: "text",

    },
    {
        name: "TESLİM ALAN",
        placeholder: "TESLİM ALAN",
        type: "text",

    },


]

export const penaltyArticleAmounts = [
    {
        id: 1,
        code: "20/1-a/1",
		penalty: 427.00,
        amount: 320.25,
    },
    {
        id:2,
        code: "20/1-d",
		penalty: 3340.00,
        amount: 2505.00,
    },
    {
        id: 3,
        code: "20/1-d-8",
		penalty: 427.00,
        amount: 320.25,
    },
    {
        id:4,
        code: "21/1",
		penalty: 1823.00,
        amount: 1367.25,
    },
    {
        id: 5,
        code: "21/5",
		penalty: 3674.00,
        amount: 2755.50,
    },
    {
        id:6,
        code: "23/2-a",
		penalty: 166.00,
        amount: 124.50,
    },
	{
        id:7,
        code: "23/2-b",
		penalty: 166.00,
        amount: 124.50,
    },
	{
        id:8,
        code: "23/3-a-1",
		penalty: 750.00,
        amount: 562.50,
    },
	{
        id:9,
        code: "23/3-a-2",
		penalty: 1536.00,
        amount: 1152.00,
    },
	{
        id:10,
        code: "23/3-b-1",
		penalty: 750.00,
        amount: 562.50,
    },
	{
        id:11,
        code: "23/3-b-2",
		penalty: 1536.00,
        amount: 1152.00,
    },
	{
        id:12,
        code: "23/3-c-1",
		penalty: 750.00,
        amount:562.50 ,
    },
	{
        id:13,
        code: "23/3-c-2",
		penalty: 1536.00,
        amount: 1152.00,
    },
	{
        id:14,
        code: "23/4",
		penalty: 3093.00,
        amount: 2319.75 ,
    },
	{
        id:15,
        code: "23/5-a",
		penalty: 9107.00,
        amount: 6830.25,
    },
	{
        id:16,
        code: "23/5-b",
		penalty: 9107.00,
        amount: 6830.25 ,
    },
	{
        id:17,
        code: "25",
		penalty: 427.00,
        amount: 320.25 ,
    },
	{
        id:18,
        code: "26/1",
		penalty: 196.00,
        amount: 147.00,
    },
	{
        id:19,
        code: "26/2",
		penalty: 1823.00,
        amount: 1367.25,
    },
	{
        id:20,
        code: "26/3",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:21,
        code: "30/1-a",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:22,
        code: "30/1-b",
		penalty: 427.00,
        amount: 320.25 ,
    },
	{
        id:23,
        code: "31/1-a",
		penalty: 196.00,
        amount: 147.00,
    },
	{
        id:24,
        code: "31/1-b",
		penalty: 888.00,
        amount: 666.00  ,
    },
	{
        id:25,
        code: "32/1",
		penalty: 196.00,
        amount: 147.00  ,
    },
	{
        id:26,
        code: "32/3",
		penalty: 1823.00,
        amount: 1367.25 ,
    },
	{
        id:27,
        code: "34/a",
		penalty: 427.00,
        amount: 320.25 ,
    },
	{
        id:28,
        code: "34/b",
		penalty: 888.00,
        amount: 666.00 ,
    },
	{
        id:29,
        code: "34/c",
		penalty: 888.00,
        amount: 666.00 ,
    },
	{
        id:30,
        code: "36/3-a",
		penalty: 3674.00,
        amount: 2755.50 ,
    },
	{
        id:31,
        code: "36/3-b",
		penalty: 3674.00,
        amount: 2755.50 ,
    },
	{
        id:32,
        code: "36/3-c",
		penalty: 3674.00,
        amount: 2755.50 ,
    },
	{
        id:33,
        code: "39/2",
		penalty: 1823.00,
        amount: 1367.25  ,
    },
	{
        id:34,
        code: "39/3",
		penalty: 739.00,
        amount: 554.25,
    },
	{
        id:35,
        code: "39/4",
		penalty: 739.00,
        amount: 554.25,
    },
	{
        id:36,
        code: "42/11",
		penalty: 1823.00,
        amount: 1367.25 ,
    },
	{
        id:37,
        code: "44/1-a",
		penalty:427.00,
        amount: 320.25 ,
    },
	{
        id:38,
        code: "44/1-b",
		penalty: 427.00,
        amount: 320.25 ,
    },
	{
        id:39,
        code: "46/2-a",
		penalty: 427.00,
        amount: 320.25,
    },
	{
        id:40,
        code: "46/2-b",
		penalty: 427.00,
        amount: 320.25 ,
    },
	{
        id:41,
        code: "46/2-c",
		penalty: 427.00,
        amount: 320.25 ,
    },
	{
        id:42,
        code: "46/2-d",
		penalty: 427.00,
        amount: 320.25,
    },
	{
        id:43,
        code: "46/2-e",
		penalty: 888.00,
        amount: 666.00 ,
    },
	{
        id:44,
        code: "46/2-f",
		penalty: 1823.00,
        amount: 1367.25 ,
    },
	{
        id:45,
        code: "46/2-g",
		penalty: 1823.00,
        amount: 1367.25 ,
    },
	{
        id:46,
        code: "46/2-h",
		penalty: 1823.00,
        amount: 1367.25 ,
    },
	{
        id:47,
        code: "46/3",
		penalty: 427.00,
        amount: 320.25,
    },
	{
        id:48,
        code: "47/1-a",
		penalty: 427.00,
        amount: 320.25 ,
    },
	{
        id:49,
        code: "47/1-b",
		penalty: 427.00,
        amount: 320.25 ,
    },
	{
        id:50,
        code: "47/1-c",
		penalty: 196.00,
        amount: 147.00,
    },
	{
        id:51,
        code: "47/1-d",
		penalty: 196.00,
        amount: 147.00,
    },
	{
        id:52,
        code: "48/5",
		penalty: 1823.00,
        amount: 1367.25 ,
    },
	{
        id:53,
        code: "48/8",
		penalty: 9411.00,
        amount: 7058.25 ,
    },
	{
        id:54,
        code: "48/9",
		penalty: 5224.00,
        amount: 3918.00,
    },
	{
        id:55,
        code: "49/3",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:56,
        code: "51/2-a",
		penalty: 427.00,
        amount: 320.25 ,
    },
	{
        id:57,
        code: "51/2-b",
		penalty: 888.00,
        amount: 666.00 ,
    },
	{
        id:58,
        code: "51/2-c",
		penalty: 1823.00,
        amount: 1367.25 ,
    },
	{
        id:59,
        code: "52/1-a",
		penalty: 196.00,
        amount: 147.00  ,
    },
	{
        id:60,
        code: "52/1-b",
		penalty: 3674.00,
        amount: 147.00  ,
    },
	{
        id:61,
        code: "52/1-c",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:62,
        code: "52/1-d",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:63,
        code: "53/1-a",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:64,
        code: "53/1-b",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:65,
        code: "53/1-c",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:66,
        code: "53/1-d",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:67,
        code: "53/2",
		penalty: 196.00,
        amount: 147.00  ,
    },
	{
        id:68,
        code: "54/1-a",
		penalty: 427.00,
        amount: 320.25,
    },
	{
        id:69,
        code: "54/1-b",
		penalty: 427.00,
        amount: 320.25 ,
    },
	{
        id:70,
        code: "55",
		penalty: 196.00,
        amount: 147.00,
    },
	{
        id:71,
        code: "56/1-a",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:72,
        code: "56/1-b",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:73,
        code: "56/1-c",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:74,
        code: "56/1-d",
		penalty: 196.00,
        amount: 147.00,
    },
	{
        id:75,
        code: "56/1-e",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:76,
        code: "57/1-a",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:77,
        code: "57/1-b",
	    penalty: 196.00,
        amount: 147.00,
    },
	{
        id:78,
        code: "57/1-c",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:79,
        code: "57/1-d",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:80,
        code: "57/1-e",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:81,
        code: "57/1-f",
		penalty: 196.00,
        amount:147.00 ,
    },
	{
        id:82,
        code: "58. Madde",
		penalty: 196.00,
        amount: 147.00,
    },
	{
        id:83,
        code: "59. Madde",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:84,
        code: "60/1-a",
        penalty: 196.00,
		amount: 147.00 ,
		
    },
	{
        id:85,
        code: "60/1-b",
        penalty: 196.00,
		amount: 147.00,
    },
	{
        id:86,
        code: "60/1-c",
        penalty: 196.00,
		amount: 147.00,
    },
	{
        id:87,
        code: "60/1-d",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:88,
        code: "60/1-e",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:89,
        code: "60/1-f",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:90,
        code: "60/1-g",
        penalty: 196.00,
		amount: 147.00  ,
    },
	{
        id:91,
        code: "60/1-h",
        penalty: 196.00,
		amount: 147.00  ,
    },
	{
        id:92,
        code: "61/1-a",
        penalty: 196.000,
		amount: 147.00 ,
    },
	{
        id:93,
        code: "61/1-b",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:94,
        code: "61/1-c",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:95,
        code: "61/1-d",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:96,
        code: "61/1-e",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:97,
        code: "61/1-f",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:98,
        code: "61/1-g",
        penalty: 196.00,
		amount: 147.00  ,
    },
	{
        id:99,
        code: "61/1-h",
        penalty: 196.00,
		amount: 147.00,
    },
	{
        id:100,
        code: "61/1-ı",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:101,
        code: "61/1-j",
        penalty: 196.00,
		amount: 147.00,
    },
	{
        id:102,
        code: "61/1-k",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:103,
        code: "61/1-l",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:104,
        code: "61/1-m",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:105,
        code: "61/1-n",
        penalty: 196.00,
		amount: 147.00,
    },
	{
        id:106,
        code: "61/1-o",
        penalty: 392.00,
		amount: 294.00 ,
    },
	{
        id:107,
        code: "63",
        penalty: 888.00,
		amount: 666.00 ,
    },
	{
        id:108,
        code: "64/1-a-1",
        penalty: 196.00 ,
		amount: 147.00,
    },
	{
        id:109,
        code: "64/1-a-2",
        penalty: 427.00,
		amount: 320.25  ,
    },
	{
        id:110,
        code: "64/1-a-3",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:111,
        code: "64/1-b-1",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:112,
        code: "64/1-b-2",
        penalty: 196.00,
		amount:147.00 ,
    },
	{
        id:113,
        code: "64/1-b-3",
        penalty: 196.00,
		amount: 147.00,
    },
	{
        id:114,
        code: "64/1-b-4",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:115,
        code: "64/1-b-5",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:116,
        code: "64/1-b-6",
        penalty: 196.00,
		amount: 147.00,
    },
	{
        id:117,
        code: "65/1-a",
        penalty: 153.00,
		amount: 114.75,
    },
	{
        id:118,
        code: "65/1-b-(a)",
        penalty: 1665.00 ,
		amount: 1248.75 ,
    },
	{
        id:119,
        code: "65/1-b-(b)",
        penalty: 3340.00,
		amount: 2505.00 ,
    },
	{
        id:120,
        code: "65/1-b-(c)",
        penalty: 5010.00,
		amount: 3757.50 ,
    },
	{
        id: 121,
        code: "65/1-b-(d)",
        penalty: 6690.00,
		amount: 5017.50,
    },
    {
        id:122,
        code: "65/1-b-(e)",
        penalty: 10036.00,
		amount: 7527.00,
    },
    {
        id:123,
        code: "65/1-c",
        penalty: 1665.00,
		amount: 1248.75,
    },
    {
        id:124,
        code: "65/1-d",
        penalty: 408.00,
		amount: 306.00,
    },
    {
        id:125,
        code: "65/1-e",
        penalty: 828.00 ,
		amount: 621.00,
    },
    {
        id:126,
        code: "65/1-f",
        penalty: 828.00 ,
		amount: 621.00,
    },
	{
        id:127,
        code: "65/1-g",
        penalty: 1665.00,
		amount: 1248.75 ,
    },
	{
        id:128,
        code: "65/1-h",
        penalty: 408.00,
		amount: 306.00,
    },
	{
        id:129,
        code: "65/1-i",
        penalty: 408.00,
		amount: 306.00,
    },
	{
        id:130,
        code: "65/1-j",
        penalty: 408.00,
		amount: 306.00,
    },
	{
        id:131,
        code: "65/1-k",
        penalty: 408.00,
		amount: 306.00,
    },
	{
        id:132,
        code: "65/4",
        penalty: 3340.00 ,
		amount:2505.00 ,
    },
	{
        id:133,
        code: "65/a",
        penalty: 1138.00,
		amount: 853.50,
    },
	{
        id:134,
        code: "66",
        penalty: 427.00,
		amount: 320.25,
    },
	{
        id:135,
        code: "67/1-a",
        penalty: 427.00,
		amount: 320.25 ,
    },
	{
        id:136,
        code: "67/1-b",
        penalty: 427.00,
		amount: 320.25,
    },
	{
        id:137,
        code: "67/1-c",
        penalty: 427.00,
		amount: 320.25 ,
    },
	{
        id:138,
        code: "67/1-d",
        penalty: 9125.00,
		amount: 6843.75 ,
    },
	{
        id:139,
        code: "68/1-a-1",
        penalty: 196.00 ,
		amount: 147.00,
    },
	{
        id:140,
        code: "68/1-a-2	",
        penalty: 196.00 ,
		amount: 147.00 ,
    },
	{
        id:141,
        code: "68/1-a-3",
        penalty: 196.00 ,
		amount: 147.00 ,
    },
	{
        id:142,
        code: "68/1-b-1",
        penalty: 196.00 ,
		amount: 147.00 ,
    },
	{
        id:143,
        code: "68/1-b-2",
        penalty: 196.00 ,
		amount: 147.00  ,
    },
	{
        id:144,
        code: "68/1-c",
        penalty: 196.00 ,
		amount: 147.00,
    },
	{
        id:145,
        code: "69/1",
        penalty: 196.00 ,
		amount: 147.00  ,
    },
	{
        id:146,
        code: "70. Madde",
        penalty: 888.00,
		amount: 666.00  ,
    },
	{
        id:147,
        code: "71. Madde",
        penalty: 196.00 ,
		amount: 147.00 ,
    },
	{
        id:148,
        code: "72. Madde",
        penalty: 196.00 ,
		amount: 147.00 ,
    },
	{
        id:149,
        code: "73/a",
        penalty: 196.00 ,
		amount: 147.00 ,
    },
	{
        id:150,
        code: "73/b",
        penalty: 196.00 ,
		amount: 147.00 ,
    },
	{
        id:151,
        code: "73/c",
        penalty: 427.00 ,
		amount: 320.25 ,
    },
	{
        id:152,
        code: "74/a",
        penalty: 888.00,
		amount: 666.00  ,
    },
	{
        id:153,
        code: "74/b",
        penalty: 888.00,
		amount: 666.00  ,
    },
	{
        id:154,
        code: "75. Madde",
        penalty: 427.00 ,
		amount: 320.25  ,
    },
	{
        id:155,
        code: "76. Madde",
        penalty: 427.00 ,
		amount: 320.25,
    },
	{
        id:156,
        code: "77/1-b",
        penalty: 427.00 ,
		amount: 320.25,
    },
	{
        id:157,
        code: "77/1-c",
        penalty: 196.00,
		amount: 147.00 ,
    },
	{
        id:158,
        code: "78/1-a",
        penalty: 196.00 ,
		amount: 147.00 ,
    },
	{
        id:159,
        code: "78/1-b",
        penalty: 196.00 ,
		amount: 147.00 ,
    },
	{
        id:160,
        code: "81/1-a",
        penalty: 427.00,
		amount: 320.25,
    },
	{
        id:161,
        code: "81/1-b",
        penalty: 427.00,
		amount: 320.25 ,
    },
	{
        id:162,
        code: "81/1-c",
        penalty: 427.00,
		amount: 320.25 ,
    },
	{
        id:163,
        code: "81/1-d",
        penalty: 427.00,
		amount: 320.25,
    },
	{
        id:164,
        code: "81/1-e",
        penalty: 427.00,
		amount:320.25 ,
    },
	{
        id:165,
        code: "81/3",
        penalty: 888.00,
		amount:666.00 ,
    },
	{
        id:166,
        code: "82/1-a",
        penalty: 427.00,
		amount: 320.25 ,
    },
	{
        id:167,
        code: "82/1-b",
		penalty: 427.00,
        amount: 320.255 ,
    },
	{
        id:168,
        code: "82/1-c",
		penalty: 427.00,
        amount: 320.25,
    },
	{
        id:169,
        code: "91. Madde",
		penalty: 196.00,
        amount: 147.00 ,
    },
	{
        id:170,
        code: "Ek-2/1",
		penalty: 1823.00,
        amount: 1367.25 ,
    },
	{
        id:171,
        code: "Ek-2/3-a",
		penalty: 9125.00,
        amount: 6843.75,
    },
	{
        id:172,
        code: "Ek-2/3-b",
		penalty: 3674.00,
        amount: 2755.50,
    },
	{
        id:173,
        code: "Ek-2/3-c",
		penalty: 1823.00 ,
        amount: 1367.25 ,
    },
	{
        id:174,
        code: "Ek 2/5",
		penalty: 1823.00 ,
        amount: 1367.25 ,
    },
	{
        id:175,
        code: "Ek-2/6",
		penalty: 1823.00 ,
        amount: 1367.25,
    },
	
]


 export const userAdminType = [
    {
        id: 1,
        name : 'System Admin',
        value: 'SYSTEM_ADMIN'
    },
    {
        id: 2,
        name : 'Admin',
        value: 'ADMIN'
    },
    {
        id: 3,
        name : 'User',
        value: 'USER'
    }
]

export const departmentType = [
    {
        secretariat: 'GENEL SEKRETER YARDIMCILIĞI (1)',
        departments: [
            {
                department: 'İNSAN KAYNAKLARI VE EĞİTİM DAİRESİ BAŞKANLIĞI',
            },
            {
                department: 'YAZI İŞLERİ VE KARARLAR DAİRESİ BAŞKANLIĞI',
            },
            {
                department: 'BİLGİ İŞLEM DAİRESİ BAŞKANLIĞI',
            },
            {
                department: 'DIŞ İLİŞKİLER DAİRESİ BAŞKANLIĞI',
            }
        ]
    },
    {
        secretariat: 'GENEL SEKRETER YARDIMCILIĞI (2)',
        departments: [
            {
                department: 'Çevre Koruma ve Kontrol Dairesi Başkanlığı',
            },
            {
                department: 'Raylı Sistem Dairesi Başkanlığı',
            }
        ]
    },
    {
        secretariat: 'GENEL SEKRETER YARDIMCILIĞI (3)',
        departments: [
            {
                department: 'Kültür Dairesi Başkanlığı',
            },
            {
                department: 'Sağlık Dairesi Başkanlığı',
            },
            {
                department: 'Sosyal Hizmetler Dairesi Başkanlığı',
            },
            {
                department: 'Kültür Varlıkları Dairesi Başkanlığı',
            },
            {
                department: 'Basın Yayın Ve Halkla İlişkiler Dairesi Başkanlığı',
            }
        ]
    },
    {
        secretariat: 'GENEL SEKRETER YARDIMCILIĞI (4)',
        departments: [
            {
                department: 'Ulaşım Dairesi Başkanlığı',
            },
            {
                department: 'İmar ve Şehircilik Dairesi Başkanlığı',
            },
            {
                department: 'Deprem Risk Yönetimi ve Kentsel İyileştirme Dairesi Başkanlığı',
            },
            {
                department: 'Boğaziçi İmar Şube Müdürlüğü',
            },
            {
                department: 'Emlak Yönetimi Dairesi Başkanlığı',
            }
        ]
    },
    {
        secretariat: 'GENEL SEKRETER YARDIMCILIĞI (5)',
        departments: [
            {
                department: 'Strateji Geliştirme Dairesi Başkanlığı',
            },
            {
                department: 'Mali Hizmetler Dairesi Başkanlığı',
            },
            {
                department: 'İştirakler Koordinasyon Şube Müdürlüğü',
            },
        ]
    },
    {
        secretariat: 'GENEL SEKRETER YARDIMCILIĞI (6)',
        departments: [
            {
                department: 'Mezarlıklar Dairesi Başkanlığı',
            },
            {
                department: 'Zabıta Dairesi Başkanlığı',
            },
            {
                department: 'Destek Hizmetleri Dairesi Başkanlığı',
            },
            {
                department: 'İtfaiye Dairesi Başkanlığı',
            },
            {
                department: 'Muhtarlık İşleri Dairesi Başkanlığı',
            }
        ]
    },
    {
        secretariat: 'GENEL SEKRETER YARDIMCILIĞI (7)',
        departments: [
            {
                department: 'Satınalma Dairesi Başkanlığı',
            },
            {
                department: 'Park Bahçe ve Yeşil Alanlar Dairesi Başkanlığı',
            },
            {
                department: 'Fen İşleri Dairesi Başkanlığı',
            },
            {
                department: 'Yol Bakım ve Altyapı Koordinasyon Dairesi Başkanlığı',
            },
            {
                department: 'Etüd ve Projeler Dairesi Başkanlığı',
            }
        ]
    },
    {
        secretariat: 'BASIN DANIŞMANI',
        departments: [
            
        ]
    },
    {
        secretariat: 'ÖZEL KALEM MÜDÜRLÜĞÜ',
        departments: [
            
        ]
    },
    {
        secretariat: 'TEFTİŞ KURULU BAŞKANLIĞI',
        departments: [
            
        ]
    },
    {
        secretariat: 'İÇ DENETİM BİRİMİ BAŞKANLIĞI',
        departments: [
            
        ]
    },
]
